### ISSUE TITLE
ImportError: cannot import name 'RoleGG' 

### ISSUE THREAD

**Issue by lhamasm** [meraki-analytics/role-identification#7]
I tried to import the libs like is show in the examples:

```
from cassiopeia.data import Role
from cassiopeia import Champion, Champions
from roleidentification import get_data, get_roles
```
but I got this error:

```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/lhamasm/.local/lib/python3.6/site-packages/roleidentification/__init__.py", line 1, in <module>
      from .utilities import get_team_roles
File "/home/lhamasm/.local/lib/python3.6/site-packages/roleidentification/utilities.py", line 1, in <module>
      from roleidentification.get_roles import iterative_get_roles, get_data, Role                                          
File "/home/lhamasm/.local/lib/python3.6/site-packages/roleidentification/get_roles.py", line 9, in <module>
      from .pull_data import get_data
File "/home/lhamasm/.local/lib/python3.6/site-packages/roleidentification/pull_data.py", line 2, in <module>
      from cassiopeia import RoleGG
ImportError: cannot import name 'RoleGG'
```

**Comment by jjmaldonis** [comment]
I'm pretty sure the champion.gg api is permanently down so our library will no longer work. At some point we'll work on replacing this.

**Comment by lhamasm** [comment]
Oh, okay. Thx. :(
Do you have any lib's suggestions for role identification?

**Comment by jjmaldonis** [comment]
People seem to be using one of these two links most recently:

https://github.com/Canisback/roleML
https://github.com/meraki-analytics/role-identification
